spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libiary?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: yq
    password: yq
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181